name: datajoint
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - spyder
  - pywin32
  - pip
  - seaborn
  - graphviz
  - git
  - pip:
    - notebook
    - datajoint==0.13.2
    - rspace-client==1.6.0
    - ipywidgets
    - ipysheet