name: datajoint
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - spyder
  - pywin32
  - pip
  - pip:
    - datajoint==0.13.2
    - element-lab==0.1.0b0
    - element-animal==0.1.0b0
    - element-session==0.1.0b0
    - element-array-ephys==0.1.0b0
    - element-calcium-imaging==0.1.0b0